# Generated by Django 2.0 on 2017-12-10 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(db_index=True, max_length=168)),
                ('source', models.CharField(max_length=30)),
                ('temperature', models.FloatField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
    ]
