# Generated by Django 2.0 on 2017-12-13 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weather',
            old_name='location',
            new_name='city',
        ),
    ]
